server:
  port: 8080

spring:
  application:
    name: StartCurso

  datasource:
    url: jdbc:postgresql://localhost:5432/startcurso
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: startcurso-secret-key-muito-secreta-e-longa-para-jwt-token
      expiration: 86400000 # 24 horas em milissegundos

# Configuração para documentação da API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
